name: demo_firebase
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  get: ^4.6.5
  provider: ^6.0.5
  google_fonts: ^5.1.0
  connectivity_plus: ^4.0.2
  bot_toast: ^4.0.4
  image_cropper: ^5.0.0
  image_picker: ^1.0.1
  permission_handler: ^10.4.5
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  keyboard_actions: ^4.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
