
class LocalizationMap {
  static Map<String, String> get codesEN => {
        "oops": "Oops!",
        "dinner":"Dinner",
        "show_more": " View more",
        "show_less": " View less",
        "email_is_required": "Email is required",
        "enter_a_valid_email": "Enter a valid email",
        "emojis_are_not_allowed_in_email_addresses": "Emojis are not allowed in the email addresses",
        "user_name_is_required": "Username is required",
        "max_user_name_chars": "Maximum 25 characters are allowed",
        "please_enter_otp": "Please enter OTP",
        "invalid_otp": "Invalid OTP",
        "please_enter_your_password": "Please enter your password",
        "password_limit": "Minimum 6 digits required",
        "password_should_contain_at_least_eight_character":
        "Password should contain at least 8 character",
        "please_enter_password": "Please enter password",
        "invalid_name": "Invalid name",
        "password_should_be_alphanumeric": "Password should be alphanumeric",
        "password_should_have_capital_alphabet":
        "Password should have a capital alphabet",
        "password_should_1_special_character":
        "Password should have 1 special character",
        "please_re_enter_your_password": "Please re-enter your password",
        "re_enter_your_password": "Reenter your password",
        "password_does_not_match": "Password does not match",
        "full_name_is_required": "Full name is required",
        "max_full_name_chars": "Maximum 60 characters are allowed",
        "max_about_field_chars" : "Maximum 250 characters are allowed",

        "press_again_to_exit": "Press again to exit",
        "connection_restored": "Connection Restored",
        "uh_oh": "Uh Oh!",
        "no_internet_connection": "No Internet Connection",
        "retry": "Retry",
        "settings": "Settings",
        "skip": "Skip",
        "onBoardingP1T1": "Order food right from the \napp",
        "continue": "Continue",
        "onBoardingP2T1": "Wait for the chef to prepare \nyour order",
        "onBoardingP3T1": "Enjoyed your meal? Rate your \norder through the app",
        "email": "Email",
        "new_email": "New Email",
        "field_cant_be_empty": "Field can't be empty",
        "max_file_name_field_chars": "Maximum 50 characters are allowed",
        "are_you_sure": "Are You Sure?",
        "yes": "Yes",
        "cancel": "Cancel",
        "delete": "Delete",
        "sort_by": "Sort By",
        "back": "Back",
        "name": "Name",
        "confirm": "Confirm",
        "get_started": "Get Started",
        "welcome_back" : "Welcome Back!",
        "password" : "Password",
        "new_password" : "New Password",
        "confirm_password" : "Confirm Password",
        "enter_your_email" : "Enter your email",
        "enter_your_num" : "Enter your Number",
        "enter_your_current_password" : "Enter your current password",
        "enter_your_new_password" : "Enter your new password",
        "create_account" : "Create Account",
        "company_id" : "Company ID",
        "full_name" : "Full Name",
        "chats" : "Chats",
        "enter_your_message" : "Enter your Message",
        "allergies" : "Add allergies if you have any",
        "i_accept_the" : "I accept the ",
        "terms_conditions" : "Terms & Conditions",
        "privacy_policy": 'Privacy Policy',
        "enter_password" : "Enter password",
        "forgot_password" : "Forgot Password?",
        "login" : "Login",
        'future_builder':'Future Builder',
        'stream_builder':'Stream Builder',
        'user_screen':'User Screen',
        "don't_have_an_acc" : "Don't have an account? ",
        "forgotten_your_password" : "Forgotten Your Password?",
        "we'll_send_you_a_verification_code" : "We'll send you a verification code on \n your email",
        "send_code" : "Send Code",
        "otp_verification" : "OTP Verification",
        "enter_otp_statement" : "Enter the OTP that you’ve received on\n your email",
        "enter_num_statement" : "Enter your Number on which you will get OTP",
        "request_again" : "Request again",
        "verify_otp" : "Verify OTP",
        "verify_your_number" : "Verify Your Number",
        "reset_password" : "Reset Password",
        "reset_pass_statement" : "Enter your new password and never share it with anyone",
        "new_pass" : "New Password",
        "confirm_pass" : "Confirm Password",
        "enter_new_password" : "Enter new password",
        "enter_new_name" : "Enter new Name",
        "update_name":'Update Name',
        "and":" and ",
        "next":" Next",
        "request_pending" : "Request Pending",
        "request_pending_statement" : "Thank you for your patience. Your request has been sent to the admin for approval. ",
        "now_servings":"Now Servings",
        "already_have_an_acc" : "Already have an account? ",
        "notification":"Notifications",
        "new":"New",
        "all_notifications":"All Notifications",
        "update_email":"Update Email",
        'upload_image':'upload Image',
        "update":"Update",

        "your_cart" : "Your Cart",
        "breakfast_choice" : "Breakfast Choice",
        "breakfast_side" : "Breakfast Side",
        "lunch_choice" : "Lunch Choice",
        "lunch_side" : "Lunch Side",
        "dinner_choice" : "Dinner Choice",
        "time_slot" : "Time Slot",
        "special_request" : "Special Request",
        "type_your_request_here" : "Type your request here...",
        "proceed" : "Proceed",
        "go_home" : "Go Home",
        "no_items_in_your_cart" : "No items in your cart",
        "go_back_to_home" : "Go back to home screen to add items in your cart",
        "history":"History",
        "breakfast":"Breakfast",
        "give_rating":"Give Rating",
        "your_order" : "Your Order",
        "discard" : "Discard",
        "completed":"Completed",
        "i_dont_need_salt_added_in_food":"I don’t need salt added in the food",
        "lunch":"Lunch",
        "pending":"Pending",
        "confirmation" : "Confirmation",
        "Your_order_has_been_placed" : "Your order has been placed!",
        "order_id" : "Order ID :",
        "change_password":"Change Password",
        "save_changes":'Save Changes',
        "enter_your_current_password":"Enter Your Current Password",
        "my_profile":"My Profile",
        "are_you_sure_you_want_to_logout?":"Are you sure you want to logout?",
        "logout":"Logout",
        "delete_account":"Delete Account",
        "delete_permission":"Are you sure you want to delete your account? This will permanently delete your account.",
        "current_password":"Current Password",
        "gallery":"Gallery",
        "camera":"Camera",
        "rate_your_order":"Rate your order",
        "the_food_was_normal":"The food was normal",
        "Please_visit_the_kitchen_get_your_order" : "Please visit the kitchen get your order",
        "view_weekly_menu" : "View Weekly Menu",
        "breakfast_Choice" : "Breakfast Choice",
        "breakfast_Side" : "Breakfast Side",
        "place_your_order" : "Place Your Order",
        "dinner_late_plate" : "Dinner Late Plate",
        "location" : "Location",
        "late_plate_in_fridge" : "Late plate in Fridge",
        "on_table_in_kitchen" : "On table in kitchen",
        "no_new_notifications" : "No new notifications",
        "no_new_notifications_desc" : "We’ll notify you whenever you get any new notifications",
        "something_missing" : "Something’s missing!",
        "something_missing_statement" : "Please make sure you’ve selected the time slot before proceeding.",
        "password_updated_successfully" : "password_updated_successfully"
      };

  static String getValue(String key) {
      return codesEN[key] ?? "";
  }
}

extension Localize on String {
      String L() {
            return LocalizationMap.getValue(this);
      }
}
